const mongoose = require('mongoose');
const shoppingCart = require('../models/shoppingCart');
const connectDB = require('../config/db');
const member = require('../models/memberModel')


connectDB();

// add to cart (POST)
// view all cart products (GET)
// change quantity of products (PATCH)
// remove from cart (DELETE)
// calculate subtotal ($) before checking out (GET)


// const cartwheel = new shoppingCart({ userId: 3842982409, });

const cartwheel = new shoppingCart({
    // cart Id is autogenerated as _id?

    memberId: member,
    purchaseTime: null,
    products: [{productId: mongoose.Schema.Types.ObjectId, quantity: 2, from: null, to: null, startShipping: null, endShipping: null, shippingID: null}],
    numShipped: null
});

console.log(cartwheel);

cartwheel.save();