const mongoose = require('mongoose');
const shoppingCart = require('../models/shoppingCart');
const connectDB = require('../config/db');
const member = require('../models/memberModel')


connectDB();


const cartwheel = new shoppingCart({
    // cart Id is autogenerated as _id?
    memberId: member,
    purchaseTime: null,
    products: [{productId: mongoose.Schema.Types.ObjectId, quantity: 2, from: null, to: null, startShipping: null, endShipping: null, shippingID: null}],
    numShipped: null
});

// console.log(cartwheel);

// cartwheel.save();



// shoppingCart.find().then((result) => console.log(result)); // lists all items

// shoppingCart.findOne({userId: 3842982409}).then((result) => console.log(result)) // finds a cart based on filter
// shoppingCart.findOneAndDelete().then((result) => console.log(result)); // finds and deletes a cart

// deleteOne() is better probably, combined with .where()
async function test(shoppingCartId) {
    
    try {
        const grabCart = await shoppingCart.findById(shoppingCartId);
        console.log(grabCart)
        grabCart.purchaseTime = Date.now();
        grabCart.save();
    } catch (error) {
        console.log(error);
    }

}
test("65418b1b8c27e7ea520ba7d2");
