const mongoose = require('mongoose');
const cartProduct = require('./cartProduct');
const Schema = mongoose.Schema;


const shoppingCartSchema = new Schema({
    // cart Id is autogenerated as _id?
    email: {
        type: String,
        required: true,
        unique: true,
      },
    purchaseTime: {
        type: Number // epoch time
    },
    products: {
        type: [cartProduct]
    },
    numShipped: {
        type: Number
    }
});

module.exports = mongoose.model('shoppingCart', shoppingCartSchema);