const mongoose = require('mongoose');
const cartProduct = require('./cartProduct.js').schema;
const Schema = mongoose.Schema;


const shoppingCartSchema = new Schema({
    // cart Id is autogenerated as _id
    email: {
        type: String,
        required: true,
        unique: true,
      },
    purchaseTime: {
        type: Number, // epoch time
        default: null
    },
    products: {
        type: [cartProduct]
    },
    numShipped: {
        type: Number,
        default: null
    }
});

module.exports = mongoose.model('shoppingCart', shoppingCartSchema);