const mongoose = require('mongoose');
const Schema = mongoose.Schema;


const shoppingCartSchema = new Schema({
    // cart Id is autogenerated as _id?
<<<<<<< HEAD
    email: {
        type: String,
        required: true,
        unique: true,
      },
=======

    userId: {
        type: String, // findById() takes in a string
        required: true
    },
>>>>>>> 0094bf2e2ab50186437d81eeaee40343f09fbe59
    purchaseTime: {
        type: Number // epoch time
    },
    products: {
        type: [{productId: String, quantity: Number, from: String, to: String, startShipping: Date, endShipping: Date, shippingID: Number}]
    },
    numShipped: {
        type: Number
    }
});

module.exports = mongoose.model('shoppingCart', shoppingCartSchema);